export interface ProjectInterface {
  labels: string[],
  title: string,
  description: string,
  term: string,
  url: string,
}

export const Projects: ProjectInterface[] = [
  {
    labels: ["Qiita", "PdM"],
    title: "ストックのシェア機能プロジェクト",
    description: "ストックのシェア機能の企画/設計を担当した。",
    term: "2025年2月〜",
    url: "https://blog.qiita.com/stock-share-beta/",
  },
  {
    labels: ["Qiita", "イベント"],
    title: "Qiita Bash",
    description: "Qiita Bashに関するイベント企画・集客・運営・配信",
    term: "2024年4月〜",
    url: "https://corp.qiita.com/releases/2024/10/qiita-bash/",
  },
  {
    labels: ["Qiita", "Accessibility", "人材育成"],
    title: "アクセシビリティ改善プロジェクト",
    description: "アクセシビリティに関する知識の浸透、人材育成、Qiitaのプロダクト改善を担当した。",
    term: "2024年4月〜",
    url: "https://blog.qiita.com/accessibility-project/",
  },
  {
    labels: ["Qiita", "Frontend", "Accessibility", "UI"],
    title: "Qiitaダークモード導入",
    description: "Qiitaにダークモードを導入するため、カラーパレットの修正、カラートークンの設計、開発を担当した。",
    term: "2023年2月〜2024年2月",
    url: "https://blog.qiita.com/release-theme/",
  },
  {
    labels: ["Qiita", "PdM"],
    title: "GitHub Sponsors 連携機能",
    description: "GitHub Sponsors 連携機能の企画/設計・プロジェクトマネジメントを担当した。",
    term: "2023年11月〜2024年1月",
    url: "https://blog.qiita.com/github-sponsors/",
  },
  {
    labels: ["Qiita", "イベント"],
    title: "Qiita Hackathon",
    description: "Qiita Hackathonに関するクリエイティブディレクションを担当した。",
    term: "2023年9月〜2023年12月",
    url: "https://corp.qiita.com/releases/2023/12/qiita-hackathon-2024-first/",
  },
  {
    labels: ["Qiita", "PdM", "UI", "UX"],
    title: "AIサジェスト機能",
    description: "機能開発の企画/設計・プロジェクトマネジメント・UXの設計・UIデザインを担当した。",
    term: "2023年8月〜2023年11月",
    url: "https://blog.qiita.com/ai-suggest-closed-beta/",
  },
  {
    labels: ["Qiita", "イベント", "UI", "UX"],
    title: "Qiita Engineer Festa 2023",
    description: "Qiita Engineer Festa 2023に関するクリエイティブディレクション・UX設計・UIデザインを担当した。",
    term: "2023年2月〜2023年8月",
    url: "https://corp.qiita.com/releases/2023/02/qiita-engineer-festa-2023-sponser/",
  },
  {
    labels: ["Qiita", "イベント", "UI", "UX", "Frontend"],
    title: "Qiita Engineer Festa 2022",
    description: "Qiita Engineer Festa 2022に関するクリエイティブディレクション・UX設計・UIデザインを担当した。",
    term: "2022年2月〜2022年8月",
    url: "https://corp.qiita.com/releases/2022/03/engineer-festa-2022/",
  },
  {
    labels: ["Qiita", "イベント", "UI", "UX"],
    title: "Qiita Advent Calendar 2021",
    description: "Qiita Advent Calendar 2021に関するクリエイティブディレクション・UX設計・UIデザインを担当した。",
    term: "2021年8月〜2021年12月",
    url: "https://corp.qiita.com/releases/2021/09/qiita-advent-calendar-2021/",
  },
  {
    labels: ["Qiita", "UI", "UX", "Frontend"],
    title: "Qiita 表彰プログラム 特設サイト",
    description: "Qiita 表彰プログラム 特設サイトに関するクリエイティブディレクション・UX設計・UIデザインを担当した。",
    term: "2021年7月〜2021年9月",
    url: "https://corp.qiita.com/releases/2021/09/qiita-award/",
  },
  {
    labels: ["Qiita", "イベント", "UI", "UX", "Frontend"],
    title: "Qiita Engineer Summit 2021",
    description: "Qiita Engineer Summit 2021に関するクリエイティブディレクション・UX設計・UIデザインを担当した。",
    term: "2021年3月〜2021年7月",
    url: "https://corp.qiita.com/releases/2021/06/qiita-engineer-summit-2021/",
  },
  {
    labels: ["Qiita", "イベント", "UI", "UX"],
    title: "Qiita エンジニアフェスタ 2021",
    description: "Qiita エンジニアフェスタ 2021に関するクリエイティブディレクション・UX設計・UIデザインを担当した。",
    term: "2021年2月〜2021年8月",
    url: "https://corp.qiita.com/releases/2021/03/qiita-engineer-festa-2021/",
  },
  {
    labels: ["Qiita Jobs", "UI", "UX"],
    title: "Qiita Jobs サービスリニューアル",
    description: "Qiita Jobs サービスリニューアルに関するUX設計・UIデザインを担当した。",
    term: "2020年6月〜2020年8月",
    url: "https://corp.qiita.com/releases/2020/08/qiita-jobs-renewal/",
  }
];
